# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_v'),
    ]

    operations = [
        migrations.RenameField(
            model_name='v',
            old_name='video',
            new_name='video1',
        ),
    ]
