# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180111_0317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V',
        ),
        migrations.AddField(
            model_name='video',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
