# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration',
            field=models.CharField(max_length=30),
        ),
    ]
