# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180112_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_etails',
            field=models.CharField(default=b'adfga', max_length=5000),
        ),
        migrations.AddField(
            model_name='registration',
            name='course_name',
            field=models.CharField(default=b'asdf', max_length=300),
        ),
    ]
